### PR TITLE
Feature/variable fix

### PR DESCRIPTION
**Pull request by ghost**
!global flag throws error in node-sass 2.1.1

### CODE REVIEW

**Comment by alienlebarge** [comment]
Next time, please do one PR per feature. It will be easier to deal with :wink:

**Comment by dirkpennings-redhotminute** [comment]
Thanks for taking the changes in account. With the flexbox module the original layout styling is altered. Therefor I introduced the classname so you have the possibility to overrule it (default behaviour isn't changed, it still targets the normal `.layout` classname, but in my case I changed it to `.layout--flex` (within the inuit config file in our project) because I don't want this behaviour as a default but as an addition.

**Comment by dirkpennings-redhotminute** [comment]
I actually didn't rename the class, but made the possibility to rename it.. :smile: 
The change on line 79 is necessary if you want to rename the class.
Good point about the PR per feature!

**Comment by dirkpennings-redhotminute** [comment]
You're right about the !global though (they can stay), but I had to add the `$inuit-generate-responsive-item-alias:  null !default;` else I got this error when compiling:

`[09:52:42] gulp-notify: [Gulp notification] unbound variable $inuit-generate-responsive-item-alias inuit-flexbox/_objects.flexbox.scss`

**Comment by alienlebarge** [comment]
Since the user as deleted his account (!), I close this PR.

**Pull request closed without merging**
